export const BCRYPT_SERVICE = "BCRYPT_SERVICE";
export const CUSTOM_LOCAL_AUTH_REPOSITORY = "CUSTOM_LOCAL_AUTH_REPOSITORY";
export const LOCAL_AUTH_PERSISTANCE_ADAPTER = "LOCAL_AUTH_PERSISTANCE_ADAPTER";
export const TYPEORM_LOCAL_AUTH_REPOSITORY = "TYPEORM_LOCAL_AUTH_REPOSITORY";
