name: "run tests"
on:
  push:
    branches:
      - master
jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v1

      - name: Setup Node.js environment
        uses: actions/setup-node@v1
        with:
          node-version: "^20.3.1"

      - name: Run install
        uses: borales/actions-yarn@v4
        with:
          cmd: install

      - name: Run tests
        uses: borales/actions-yarn@v4
        with:
          cmd: test:cov

      - name: Check coverage
        run: |
          coverage=$(jq '.total[].pct' < ./coverage/coverage-summary.json | awk '{s+=$1} END {print (s/4)}')
          echo "Test coverage: $coverage %"
          if [ $coverage -lt 50 ]; then
            echo "Test coverage is less than 50%"
            exit 1
          fi
